### ISSUE TITLE
STM32f407 Standard

### ISSUE THREAD

**Issue by uControllerLab** [moonglow/pcan_pro_x#13]
Standard usb pin on most devebox stm32f407 is 

PA11 USB_DM
PA12 USB_DP

Can you please make CubeMX project to easy  change pin configuration

Thanks

**Comment by moonglow** [comment]
@uControllerLab Hi !

>Standard usb pin on most devebox stm32f407 is

I already explain here ( #6 ) about USB, i need more USB endpoints that's why i use **USB HS in FS mode** and this peripheral located on another pins. 

>Can you please make CubeMX project to easy change pin configuration

Sorry but it is useless i do not use CubeMX peripheral config for most already made peripheral.

**Comment by uControllerLab** [comment]
Thank you for the explanation!

it work with devebox black stm32f407 when make bridge
PA11->PB14
PA12->PB15
