### ISSUE TITLE
stm32f407ve report assert on protocol.c

### ISSUE THREAD

**Issue by kvvipa0028** [moonglow/pcan_pro_x#17]
Hello.  I try myself to build pro on this project. when i connect to windows, report assert on protocol.c  Line 809. 
protocol_process_data   :   assert( 0 );

**Comment by moonglow** [comment]
Hi ! That means that  PEAK added new type of record. Try to use [older drivers](https://github.com/slimelec/ollie-hw/issues/8#issuecomment-1016068990) for adapter or try to implement that record. PEAK CEO told me that i need to stop my development for that projects. Thats why i can't provides new updates.

**Comment by kvvipa0028** [comment]
Ouch.I mean 'XCAN'. Thanks!!!   Ps. use fd version is ok.

**Comment by zhangjingliu** [comment]
> Hi ! That means that PEAK added new type of record. Try to use [older drivers](https://github.com/slimelec/ollie-hw/issues/8#issuecomment-1016068990) for adapter or try to implement that record. PEAK CEO told me that i need to stop my development for that projects. Thats why i can't provides new updates.

You are a genius, you shoul ignore the PEAK CEO, because you finish him
