### ISSUE TITLE
why i cannot setup usbdriver in window10?

### ISSUE THREAD

**Issue by cs2132** [moonglow/pcan_pro_x#2]
I  have been used your code ,and has been run.but windows10 cannot set up the usbcan's driver,errcode 31.
![1611240174(1)](https://user-images.githubusercontent.com/26681437/105366205-0663e280-5c3a-11eb-8499-359b7ec8ce31.png)

**Comment by moonglow** [comment]
Hi,
Please provide me more information about your setup.

1. What hardware board you use.
2. What firmware version you use.

Be aware if your build firmware yourself, you need to use provided HAL libraries it will not works correctly with original HAL lib. Can you check how it works with different PC if it possible. Thank you.

**Comment by cs2132** [comment]
how to find firmware version? It should be the latest code。  I used  your provided HAL lib in keil 5 。If I use "pcanpro_protocol.c" file and define PCAN_PRO,  the Window10 can't enumerate. If I use "pcanpro_fd_protocol.c" fileand  define  PCAN_FD, the system can enumerate successfully（“PCAN-USB FD”）. I wonder if there is something wrong with the descriptor of PCAN_PRO.

**Comment by cs2132** [comment]
could you give me your email? I'll send you my code to have a look.

**Comment by moonglow** [comment]
Ah... you build firmware yourself with Keil. First of all you can try prebuild firmwares, from here: https://github.com/moonglow/pcan_pro_x/releases

Another thing, make sure what you define needed DEFINES while you build your code ( you can check all needed info from Makefile ). As example all PRO versions needs INCLUDE_LIN_INTERFACE. As example for PCAN PRO, you must define

PCAN_PRO=1
INCLUDE_LIN_INTERFACE=1

I try to test all modes before release it, so i think there is no problems. I also will try to retest PCAN PRO firmware to make sure what all is OK. But my build toolchain is slightly different than yours , so i recommend you to use same toolchain or try prebuild binaries for testing.

>could you give me your email? I'll send you my code to have a look.

you can leave your e-mail here and i will contact to you.

**Comment by moonglow** [comment]
I did some tests ( with builds from release page ) all works fine. I recommend you to try builds from release page first or more carefully check your Keil project settings and provided defines.

**Comment by moonglow** [comment]
closed for no inactivity.

**Comment by JustQY** [comment]
i have the same issue,and i use f205rc+usb3300,worked on 480Mbit mode,does this mode have problem?

**Comment by JustQY** [comment]
oh,i know,you modified the code of usb lib,when i merged, the driver is ok,and the pcan-view shows the device

**Comment by FrancisChuh** [comment]
I met the same issue. And I use stm32g4. Build by Keil. My email francischu601@gmail.com. could you help me to have a look? Thank you. @cs2132 @moonglow @JustQY
